# Generated by Django 4.1.2 on 2022-10-20 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="autor",
            old_name="nome_autor",
            new_name="nome",
        ),
    ]
