# Generated by Django 4.1.2 on 2022-10-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_nome_autor_autor_nome"),
    ]

    operations = [
        migrations.AddField(
            model_name="autor",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
