# Generated by Django 4.1.2 on 2022-11-17 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_livro_capa"),
    ]

    operations = [
        migrations.RenameField(
            model_name="livro",
            old_name="preço",
            new_name="preco",
        ),
    ]
