# Generated by Django 4.0.5 on 2022-07-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_categoria_descricao_alter_editora_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='preço',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='quantidade',
            field=models.IntegerField(null=True),
        ),
    ]
