# Generated by Django 4.1.2 on 2022-11-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_rename_autor_livro_autores"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livro",
            name="preco",
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
